### ISSUE TITLE
batch replay gain removal

### ISSUE THREAD

**Issue by trattaa** [KnightDanila/BAT_FFMPEG#1]
Возможно ли сделать пакетное удаление Replay Gain по [этому](https://stackoverflow.com/questions/45593382/ffmpeg-remove-lame-replaygain-tag-from-mp3) примеру.
Конкретней, если запустить bat, то он бы пакетно удалил из всех mp3 replay gain, включая вложенные папки, а новое имя было бы точно такое же как у оригинала, ну или просто к новому имени добавлялся какой-нибудь символ, а старый удалялся

**Comment by trattaa** [comment]
More specifically, if you run bat, it would batch remove all replay gain from all mp3s, and the new name would be exactly the same as the original

**Comment by KnightDanila** [comment]
Hi, can you add some sample mp3 (or part of mp3) - for tests

**Comment by trattaa** [comment]
https://dropmefiles.com/iHjfn
![2020-06-30_004725](https://user-images.githubusercontent.com/44088228/86059389-521b2880-ba6b-11ea-8355-8758c3b5b56a.jpg)

**Comment by KnightDanila** [comment]
Hello, thank you for sample :)
Now I can say it is possible :bug: 
I found it in source code of ffmpeg
https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/f_sidedata.c#L88
So theoretically, it is possible to remove it from metadata without full reconverting
I am working on it :)

**Comment by KnightDanila** [comment]
Hello, after a while I found out how to do that :)

Audio-ToMP3_RemoveSideData.bat
https://github.com/KnightDanila/BAT_FFMPEG/blob/master/Audio-ToMP3_RemoveSideData.bat

This bat file doesn't reconvert the original mp3 - because it is the fastest way. In the same way, it doesn't change the original quality.
But on the other hand, it removes all sidedata from metadata (but save all metadata)
Read this about sidedata and lameinfo (xing) "not officially part of the mp3 specification"
https://eyed3.readthedocs.io/en/latest/plugins/lameinfo_plugin.html

It does not work with subfolders yet, but I am working on it :)

Test it and write if it works :racing_car:

**Comment by KnightDanila** [comment]
It does not work with subfolders yet, but I am working on it :)

**Comment by trattaa** [comment]
I confirm the work of this script, thanks for the help. I will wait for the update
